jwt:
  secret: H7oIaBujRo6fA/a0wdk09iY6STECQZbemMj8bcs5xBMzd0IYxzT+hNQd+fgXvsyz3qHF3DIwuYXUE9m7w5tkDw==

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@112.221.156.34:12345:xe
    username: KH07_KYS
    password: KH1234     

  mail:
    username: kysman2580@gmail.com
    password: hxjlsdyhsuutrdii

naver:
  client:
      id: AXQYWNUrEmFB7nHkejon    # 네이버 개발자 센터에서 발급받은 클라이언트 ID로 변경
      secret: eYdOcH2FpL    # 네이버 개발자 센터에서 발급받은 클라이언트 시크릿으로 변경
  api:
     url: https://openapi.naver.com
     path: /v1/search/news